#!/bin/bash

mkdir -p /opt/hiveden
chmod 644 /opt/hiveden

# Install all Python dependencies via pip
pip3 install --no-warn-script-location click fastapi uvicorn docker PyYAML psutil lxc paramiko websockets pihole6api yoyo-migrations 2>/dev/null || true
